## http://wiki.ros.org/navigation/Tutorials/RobotSetup#Costmap_Configuration_.28local_costmap.29_.26_.28global_costmap.29
local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  # The "publish_frequency" parameter determines the rate, in Hz, at which the costmap will publish visualization information. 
  publish_frequency: 2.0
  #  The "static_map" parameter determines whether or not the costmap should initialize itself based on a map served by the map_server. If you aren't using an existing map or map server, set the static_map parameter to false. 
  static_map: true
  # Setting the "rolling_window" parameter to true means that the costmap will remain centered around the robot as the robot moves through the world.
  rolling_window: true
  # The "width," "height," and "resolution" parameters set the width (meters), height (meters), and resolution (meters/cell) of the costmap. Note that its fine for the resolution of this grid to be different than the resolution of your static map, but most of the time we tend to set them equally. 
  width: 6.0
  height: 6.0
  resolution: 0.05
