scan_filter_chain:
- name: shadows
  type: ScanShadowsFilter
  params:
    min_angle: 10
    max_angle: 170
    neighbors: 20
    window: 1
- name: range
  type: LaserScanRangeFilter
  params:
    lower_threshold: 0.3
    upper_threshold: 9   # see spur.gzebo.xacro gazebo/sensor/ray/range/max
